networks:
  main:

services:
  server:
    image: caddy
    volumes:
      - "./public/:/srv/"
    command: "caddy file-server"
    ports:
      - 8000:80
    networks:
      main:
        aliases:
          - site.test.dev
